-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.users (id uuid NOT NULL DEFAULT gen_random_uuid(), email text NOT NULL, password_hash text NOT NULL, role user_role NOT NULL DEFAULT 'staff'::user_role, name text NOT NULL, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()));
CREATE TABLE public.villas (id uuid NOT NULL DEFAULT gen_random_uuid(), name text NOT NULL, capacity integer NOT NULL, base_rate_per_night numeric NOT NULL, description text, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), base_breakfast smallint NOT NULL DEFAULT '0'::smallint, display_id text);
CREATE TABLE public.guests (id uuid NOT NULL DEFAULT gen_random_uuid(), full_name text NOT NULL, email text, phone_number text NOT NULL, id_card_number text, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), display_id text);
CREATE TABLE public.bookings (id uuid NOT NULL DEFAULT gen_random_uuid(), guest_id uuid, check_in_date date NOT NULL, check_out_date date NOT NULL, total_guests integer NOT NULL, total_price numeric NOT NULL, status booking_status NOT NULL DEFAULT 'pending'::booking_status, notes text, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), amount_paid numeric DEFAULT 0.00, payment_status text NOT NULL DEFAULT 'pending'::text, display_id text, discount_id uuid, discount_amount numeric DEFAULT 0.00, CONSTRAINT check_payment_status CHECK (payment_status = ANY (ARRAY['pending'::text, 'partial'::text, 'complete'::text, 'cancelled'::text])));
CREATE TABLE public.finances (id uuid NOT NULL DEFAULT gen_random_uuid(), booking_id uuid, type text NOT NULL, amount numeric NOT NULL, category text NOT NULL, transaction_date date NOT NULL DEFAULT CURRENT_DATE, description text, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), order_id uuid, status text NOT NULL DEFAULT 'approved'::text, display_id text);
CREATE TABLE public.addons (id uuid NOT NULL DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), base_breakfast smallint NOT NULL DEFAULT '0'::smallint, price numeric NOT NULL DEFAULT 0.00, is_per_night boolean NOT NULL DEFAULT false);
CREATE TABLE public.booking_addons (id uuid NOT NULL DEFAULT gen_random_uuid(), booking_id uuid, addon_id uuid, quantity integer NOT NULL DEFAULT 1, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), unit_price numeric NOT NULL DEFAULT 0.00, subtotal numeric);
CREATE TABLE public.menu_items (id uuid NOT NULL DEFAULT gen_random_uuid(), name text NOT NULL, category menu_category NOT NULL DEFAULT 'food'::menu_category, price numeric NOT NULL, is_available boolean NOT NULL DEFAULT true, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()));
CREATE TABLE public.orders (id uuid NOT NULL DEFAULT gen_random_uuid(), booking_id uuid, staff_note text, total_amount numeric NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'open'::text, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), CONSTRAINT orders_status_check CHECK (status = ANY (ARRAY['open'::text, 'served'::text, 'billed'::text])));
CREATE TABLE public.order_items (id uuid NOT NULL DEFAULT gen_random_uuid(), order_id uuid, menu_item_id uuid, quantity integer NOT NULL DEFAULT 1, unit_price numeric NOT NULL, subtotal numeric, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), unit_cost numeric NOT NULL DEFAULT 0.00);
CREATE TABLE public.booking_villas (id uuid NOT NULL DEFAULT gen_random_uuid(), booking_id uuid NOT NULL, villa_id uuid NOT NULL, rate_per_night numeric NOT NULL, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), nights integer NOT NULL);
CREATE TABLE public.discounts (id uuid NOT NULL DEFAULT gen_random_uuid(), code text NOT NULL, name text NOT NULL, type text NOT NULL, value numeric NOT NULL, scope text NOT NULL, status text NOT NULL DEFAULT 'active'::text, created_at timestamp with time zone DEFAULT timezone('utc'::text, now()), villa_id uuid, application_rule text NOT NULL DEFAULT 'all_items'::text);

CREATE TYPE public.booking_status AS ENUM ('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'completed');
CREATE TYPE public.finance_category AS ENUM ('room_revenue', 'fb_revenue', 'addon_revenue', 'operational_expense', 'salary', 'maintenance', 'marketing', 'other');
CREATE TYPE public.finance_type AS ENUM ('income', 'expense');
CREATE TYPE public.menu_category AS ENUM ('food', 'beverage', 'snack', 'dessert', 'partner_kitchen', 'other');
CREATE TYPE public.user_role AS ENUM ('owner', 'admin', 'staff');